;/*FB_PKG_DELIM*/

__d("ImageExif",["exif-js"],(function(t,n,r,o,a,i){n("exif-js").enableXmp();var e={readFromFile:function(n,r){var t=new FileReader;t.addEventListener("load",function(t){var n=t.target.result,o=e.readFromArrayBuffer(n);r(o)},!1),t.readAsArrayBuffer(n)},readFromArrayBuffer:function(t){return n("exif-js").readFromBinaryFile(t)}};a.exports=e}),null);
__d("MediaManagerDispatcher",["ExplicitRegistrationReactDispatcher"],(function(t,n,r,o,a,i,l){"use strict";var e=new(r("ExplicitRegistrationReactDispatcher"))({strict:!0});l.default=e}),98);
__d("VideoStatusType",[],(function(t,n,r,o,a,i){var e=Object.freeze({ENCODING:1,DELETED:2,ENCODED:3,UPLOADING:5,OK:6,TOO_LONG:7,ENCODE_FAILED:8,UNPUBLISHED:9,SOFT_DELETED:10,UNDISCOVERABLE:11,UPLOAD_FAILED:13,UPLOADED:14,ORIGINAL_VIDEO_DELETED:15});i.default=e}),66);
__d("XAsyncRequest",["cr:1042"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:1042")}),98);
__d("XAsyncRequestWWW",["AsyncRequest"],(function(t,n,r,o,a,i,l){var e=(function(){function e(e){var t=this;this.setAllowCrossPageTransition=function(e){return t.$1.setAllowCrossPageTransition(e),t},this.$1=new(r("AsyncRequest"))(e)}var t=e.prototype;return t.setURI=function(t){return this.$1.setURI(t),this},t.setTimeoutHandler=function(t,n){return this.$1.setTimeoutHandler(t,n),this},t.setOption=function(t,n){return this.$1.setOption(t,n),this},t.setMethod=function(t){return this.$1.setMethod(t),this},t.setAutoProcess=function(t){return this.$1.setOption("suppressEvaluation",t),this},t.setData=function(t){return this.$1.setData(t),this},t.setHandler=function(t){return this.$1.setHandler(t),this},t.setPayloadHandler=function(t){return this.setHandler(function(e){return t(e.payload)}),this},t.setErrorHandler=function(t){return this.$1.setErrorHandler(t),this},t.send=function(){return this.$1.send(),this},t.abort=function(){this.$1.abort()},t.setReadOnly=function(t){return this.$1.setReadOnly(t),this},t.setAllowCrossOrigin=function(t){return this.$1.setAllowCrossOrigin(t),this},t.setAllowCredentials=function(t){return this.$1.setAllowCredentials(t),this},e})();l.default=e}),98);
__d("XCometPageEventsTabControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/{vanity}/events/",Object.freeze({ref:""}),void 0),s=e;l.default=s}),98);
__d("XCometSettingsControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/settings/",Object.freeze({show_dialog:!1,show_recommendable_nux:!1}),void 0),s=e;l.default=s}),98);
__d("XFBRightsManagerPenaltySystemStatus.facebook",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum").Mirrored(["NOT_ELIGIBLE","NO_PENALTY","PENALTY_ENFORCED","PENALTY_LIFTED"]),l=e;i.default=l}),66);
__d("fastDeepCopy",[],(function(t,n,r,o,a,i){"use strict";function e(e){return typeof e=="object"&&e!==null?l(e):e}function l(e){var t=typeof e.constructor=="function"?e.constructor():{};if(Array.isArray(e))for(var n=0;n<e.length;++n){var r=e[n];t[n]=typeof r=="object"&&r!==null?l(r):r}else for(var o in e){var a=e[o];t[o]=typeof a=="object"&&a!==null?l(a):a}return t}i.default=e}),66);
__d("getScrollPosition",["getDocumentScrollElement","getUnboundedScrollPosition"],(function(t,n,r,o,a,i,l){"use strict";function e(e){var t=r("getDocumentScrollElement")(e.ownerDocument||e.document);e.Window&&e instanceof e.Window&&(e=t);var n=r("getUnboundedScrollPosition")(e),o=e===t?e.ownerDocument.documentElement:e,a=e.scrollWidth-o.clientWidth,i=e.scrollHeight-o.clientHeight;return n.x=Math.max(0,Math.min(n.x,a)),n.y=Math.max(0,Math.min(n.y,i)),n}l.default=e}),98);