;/*FB_PKG_DELIM*/

__d("BizInboxSavedReplyContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext(Object.freeze({})),c=u;l.default=c}),98);
__d("FBAApplySavedResponseMutation_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="24295427433378889"}),null);
__d("FBAApplySavedResponseMutation.graphql",["FBAApplySavedResponseMutation_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e=(function(){var e=[{defaultValue:null,kind:"LocalArgument",name:"input"}],t=[{alias:null,args:[{kind:"Variable",name:"data",variableName:"input"}],concreteType:"SavedResponseApplyResponsePayload",kind:"LinkedField",name:"saved_response_apply",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"applied_saved_response_id",storageKey:null}],storageKey:null}];return{fragment:{argumentDefinitions:e,kind:"Fragment",metadata:null,name:"FBAApplySavedResponseMutation",selections:t,type:"Mutation",abstractKey:null},kind:"Request",operation:{argumentDefinitions:e,kind:"Operation",name:"FBAApplySavedResponseMutation",selections:t},params:{id:n("FBAApplySavedResponseMutation_facebookRelayOperation"),metadata:{},name:"FBAApplySavedResponseMutation",operationKind:"mutation",text:null}}})();a.exports=e}),null);
__d("FBAApplySavedResponseMutation",["FBAApplySavedResponseMutation.graphql","RelayModern"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e!==void 0?e:e=n("FBAApplySavedResponseMutation.graphql");function u(e,t){return o("RelayModern").commitMutation(e,{mutation:s,variables:{input:{saved_response_id:t}}})}l.commit=u}),98);
__d("MacroSpan.react",["cx","XUICloseButton.react","react"],(function(t,n,r,o,a,i,l,s){"use strict";var e,u=e||(e=o("react")),c=(function(e){function t(){for(var t,n=arguments.length,r=new Array(n),o=0;o<n;o++)r[o]=arguments[o];return t=e.call.apply(e,[this].concat(r))||this,t.$3=function(){t.props.onRemoveToken(t.props.offsetKey)},babelHelpers.assertThisInitialized(t)||babelHelpers.assertThisInitialized(t)}babelHelpers.inheritsLoose(t,e);var n=t.prototype;return n.render=function(){var e=this.$1();return e===null?null:u.jsx("span",{children:u.jsxs("span",{className:"_vxe",contentEditable:!1,"data-offset-key":this.props.offsetKey,spellCheck:!1,children:[this.$2(e),u.jsx(r("XUICloseButton.react"),{className:"_vxf",onClick:this.$3,size:"small"})]})})},n.$2=function(t){var e=t.data.key;return e in this.props.tokens?this.props.tokens[e].key:e},n.$1=function(){return this.props.entityKey==null?null:this.props.contentState.getEntity(this.props.entityKey)},t})(u.Component);l.default=c}),98);
__d("PagesApplySavedResponseMutation_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="9984707614909113"}),null);
__d("PagesApplySavedResponseMutation.graphql",["PagesApplySavedResponseMutation_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e=(function(){var e=[{defaultValue:null,kind:"LocalArgument",name:"input"}],t=[{alias:null,args:[{kind:"Variable",name:"data",variableName:"input"}],concreteType:"PageSavedResponseApplyResponsePayload",kind:"LinkedField",name:"page_saved_response_apply",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"applied_saved_response_id",storageKey:null}],storageKey:null}];return{fragment:{argumentDefinitions:e,kind:"Fragment",metadata:null,name:"PagesApplySavedResponseMutation",selections:t,type:"Mutation",abstractKey:null},kind:"Request",operation:{argumentDefinitions:e,kind:"Operation",name:"PagesApplySavedResponseMutation",selections:t},params:{id:n("PagesApplySavedResponseMutation_facebookRelayOperation"),metadata:{},name:"PagesApplySavedResponseMutation",operationKind:"mutation",text:null}}})();a.exports=e}),null);
__d("PagesApplySavedResponseMutation",["BIZInboxClientLoggerUtils","PagesApplySavedResponseMutation.graphql","RelayFBEnvironment","RelayModern"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e!==void 0?e:e=n("PagesApplySavedResponseMutation.graphql");function u(e,t,n,a,i){n===void 0&&(n=null),a===void 0&&(a=null),i===void 0&&(i=null);var l=o("BIZInboxClientLoggerUtils").getInboxPlatformAndUserType(t);return o("RelayModern").commitMutation(n!=null?n:r("RelayFBEnvironment"),{mutation:s,variables:{input:{saved_response_id:e,platform:l.inboxPlatform,source:a,page_id:i}}})}l.commit=u}),98);
__d("SavedRepliesSourceUtils.facebook",["$InternalEnumUtils","SavedRepliesSource"],(function(t,n,r,o,a,i,l){var e=o("$InternalEnumUtils").createToJSEnum(r("SavedRepliesSource")),s=o("$InternalEnumUtils").createFromJSEnum(r("SavedRepliesSource"));l.toJSEnum=e,l.fromJSEnum=s}),98);
__d("getMacrosInputDecorator",["CompositeDraftDecorator","MacroSpan.react","getEntityMatcher"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t){return new(r("CompositeDraftDecorator"))([{strategy:r("getEntityMatcher")(function(e){return e.getType()==="TOKEN"}),component:r("MacroSpan.react"),props:{onRemoveToken:t,tokens:e}}])}l.default=e}),98);
__d("SavedResponsesTokensUtils",["createEditorStateWithRanges","getMacrosInputDecorator"],(function(t,n,r,o,a,i,l){"use strict";var e=new RegExp("{{(.*?)}}","ig");function s(t){for(var n=t,r=[],o;o=e.exec(n);){var a={text:o[0],offset:o.index,length:o[0].length,entity:{token:o[0],key:o[1]}};r.push(a),n=n.replace(o[0],a.text),e.lastIndex=a.offset+a.length}if(r.length>0){r[0].offset===0&&(n=" "+n,r.forEach(function(e){e.offset++}));var i=r[r.length-1];i.length+i.offset===n.length&&(n+=" ")}return{ranges:r,text:n}}function u(e,t,n){var o=s(e),a=o.ranges,i=o.text;return r("createEditorStateWithRanges")({text:i,ranges:a,decorator:r("getMacrosInputDecorator")(n,t),addEntityToContentStateFn:function(t,n){var e=t.entity;return n.createEntity("TOKEN","IMMUTABLE",e)}})}function c(e,t){var n=e.match(/\{{(.*?)\}}/g),r=!1;return n!=null&&n.forEach(function(n){var o=n.replace("{{","").replace("}}",""),a=o;o in t?a=t[o].value:r=!0,e=e.replace(n,a)}),[e,r]}l._parseTemplateFieldTokens=s,l.createTemplateFieldsEditorStateWithText=u,l.prepareforSend=c}),98);