;/*FB_PKG_DELIM*/

__d("EmoticonRenderer",["EmoticonsList"],(function(t,n,r,o,a,i,l){"use strict";var e=["LIKE","PACMAN","FACE_WITH_COLON_THREE"];function s(t){for(var n=[],r=new RegExp(o("EmoticonsList").regexp),a=0,i=t.match(r);i!==null;){var l=i[1],s=i[2].split(""),u=o("EmoticonsList").emotes[i[2]],c=o("EmoticonsList").emoji[u];n.push({chars:s,isCustom:e.includes(c),key:c,offset:a+i.index+l.length}),a+=i.index+i[0].length,i=t.slice(a).match(r)}return n}function u(e,t,n){var r=s(e),o=[],a=0;return r.forEach(function(r){var i=r.offset;i>a&&o.push(e.substr(a,i-a)),r.isCustom?o.push(n(r.key,r.chars)):o.push(t(r.key)),a=i+r.chars.length}),o.push(e.substr(a,e.length-a)),o}l.parse=s,l.render=u}),98);
__d("LSContactGender",[],(function(t,n,r,o,a,i){var e=Object.freeze({UNKNOWN:0,FEMALE:1,MALE:2,NEUTER:3});i.default=e}),66);
__d("LSContactIdType",[],(function(t,n,r,o,a,i){var e=Object.freeze({UNKNOWN:0,FBID:1,SMS_LOCAL_ID:2});i.default=e}),66);
__d("LSContactType",[],(function(t,n,r,o,a,i){var e=Object.freeze({UNKNOWN:0,USER:1,PAGE:2,PAGE_PERSONA:3});i.default=e}),66);
__d("LSContactViewerRelationship",[],(function(t,n,r,o,a,i){var e=Object.freeze({UNKNOWN:0,NOT_CONTACT:1,CONTACT_OF_VIEWER:2,FACEBOOK_FRIEND:3,SOFT_CONTACT:4});i.default=e}),66);
__d("LSContactWorkForeignEntityType",[],(function(t,n,r,o,a,i){var e=Object.freeze({UNKNOWN:0,FOREIGN:1,NOT_FOREIGN:2,NOT_FOREIGN_LIMITED:3});i.default=e}),66);
__d("LSVerifyContactRowExistsStoredProcedure",["LSSynchronousPromise","LSVerifyContactRowExists","Promise","cr:8709"],(function(t,n,r,o,a,i,l){var e;function s(t,a){var i=t.storedProcedure(r("LSVerifyContactRowExists"),a.id,a.contactIdType,a.profilePictureUrl,a.name,a.contactType,a.profilePictureFallbackUrl,a.profilePictureUrlExpirationTimestampMs,a.urlExpirationTimestampMs,a.normalizedNameForSearch,a.isMemorialized,a.isBlocked,a.blockedByViewerStatus,a.canViewerMessage,a.isSelf,a.authorityLevel,a.capabilities,a.capabilities2,a.workForeignEntityType,a.gender,a.contactViewerRelationship,a.secondaryName,a.firstName,a.friendshipStatus);return(e||(e=n("Promise"))).resolve(o("LSSynchronousPromise").maybeExtractValueIfSynchronousPromise(i))}l.default=s}),98);
__d("MAWSharedProtocolQueueConst",["$InternalEnum"],(function(t,n,r,o,a,i){"use strict";var e=n("$InternalEnum")({Initializing:"initializing",Failed:"failed",Processing:"processing",Complete:"complete"});i.OfflineConsumerStatus=e}),66);
__d("UFICommentFileInputAcceptValues.experimental",["cr:27633"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:27633")}),98);
__d("UFICommentFileInputAcceptValuesJSModuleWrapper",["UFICommentFileInputAcceptValues"],(function(t,n,r,o,a,i,l){"use strict";l.default=r("UFICommentFileInputAcceptValues")}),98);
__d("cometIsMimeTypeForMedia",["FBLogger","UFICommentFileInputAcceptValues.experimental"],(function(t,n,r,o,a,i,l){"use strict";var e={file:null,photo:null,video:null},s={"image/gif":"video","image/webp":"video"};function u(e){return e.split(",").map(function(e){return e.trim()}).map(function(e){return e.replace(/\/\*$/,"/")})}function c(t,n,o){e[t]==null&&(e[t]=u(o));var a=e[t];if(a==null)throw r("FBLogger")("ufi2").mustfixThrow("CometIsMimeTypeForMedia prefixes can't be null");var i=s[n];return i!=null?i===t:a.some(function(e){return n.startsWith(e)})}function d(e){return c("photo",e,r("UFICommentFileInputAcceptValues.experimental").photos)}function m(e){return c("video",e,r("UFICommentFileInputAcceptValues.experimental").videos)}function p(e){return c("file",e,r("UFICommentFileInputAcceptValues.experimental").files)}l.isMimeTypeForPhoto=d,l.isMimeTypeForVideo=m,l.isMimeTypeForFile=p}),98);